### ISSUE TITLE
Fixes and improvements. 

### ISSUE THREAD

**Issue by evilezh** [intelsdi-x/snap-plugin-collector-processes#29] opened 2016-11-15 12:49 UTC
First of all, it takes only short path.
So, if you have processes:
`snap-plugin-collector-cpu`
`snap-plugin-collector-df`
`snap-plugin-collector-interface`
etc.
then you will have only 1 process: `snap-plugin-col`  . or something like this. Which is fail.
So - use full cmd name, where possible. Decode short if full not available.

Next issue. Namespace and unique entries.
I would suggest the following:
First of all, please do not put dynamic elements and static in same slot and add per PID.
for example:
`/intel/procfs/processes/<name>`
`/intel/procfs/processes/dead`
`/intel/procfs/processes/running`
etc. in this case  you can process data only by filtering out "known" values (dead/runing...) and assuming that remaining is process names. And what if you add new parameter
What i propose is:
`/intel/procfs/processes/names/<name>`
`/intel/procfs/processes/dead`
`/intel/procfs/processes/running`
Where you can explicit select "names" and know that there goes only names.
Now it is grouped by names - i suggest to group by PID: 
`/intel/procfs/processes/pid/<pid>/<name>`
In this case - you do not need to group items, you have clear visibility of what and how much items run.

remove:
`ps_count` as not necessary anymore.
add:
`ps_cmd_line`: Process command line with full path and args
`ps_cmd`: Process command line with full path

.. if you want only list of running processes: you include `ps_cmd`.
.. want to check which arguments program is using: `ps_cmd_line`
.. detect process restarts `pid inside path`

I've that implemented some time ago, will submit pull request a bit later.

**Comment by mkleina** [comment] 2017-02-14 13:57
First part of this issue is duplicate of #35

**Closed** 2017-06-01 14:23 UTC
Labels: bug, tracked
